name: GitHub Actions test
on: push
run-name: ${{ github.actor }} is testing GitHub Actions
jobs:
  sayhello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files
        run: ls -la ${{ github.workspace }}
      - name: Print repository variable ILIKE
        run: echo 'I LIKE ${{ vars.ILIKE }}'