name: CI on PR
run-name: ${{ github.actor }} is PRing
on:
  pull_request:
    branches:
      - main
jobs:
  sayhello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List files
        run: ls -a1 ${{ github.workspace }}
      - name: Say hello
        run: echo "Hello ${{ github.actor }}"