on:
  push:
    branches:
      - main
jobs:
  echo-test:
    runs-on: ubuntu-latest
    steps:
      - name: print test
        run: echo test
      - name: check repo files
        run: ls ${{ github.workspace }}
      - name: check index.js
        run: cat ${{ github.workspace }}/index.js
